import type { EnemyDefinition } from './types'

export const enemyDefinitions = [
  {
    id: 'enemy_fungorro_crawler',
    name: 'Fungorro Rastejante',
    level: 1,
    maxHp: 8,
    mitigation: 1,
    attackPower: 3,
    xpReward: 15,
    goldReward: 8,
    boundResonanceReward: 12,
    lootDefinitionIds: ['drop_fungal_nucleus'],
    skillIds: [],
    weaknessTags: ['light', 'fire'],
    assetId: 'enemy.fungorro-crawler',
    status: 'BALANCE_DRAFT',
  },
  {
    id: 'enemy_spore_sower',
    name: 'Semeador de Esporos',
    level: 2,
    maxHp: 8,
    mitigation: 1,
    attackPower: 2,
    xpReward: 25,
    goldReward: 7,
    boundResonanceReward: 10,
    lootDefinitionIds: ['drop_spore_cluster'],
    skillIds: ['skill_spore_burst'],
    aiSkillEveryRounds: 2,
    weaknessTags: ['light', 'fire'],
    assetId: 'enemy.spore-sower',
    status: 'BALANCE_DRAFT',
  },
] satisfies EnemyDefinition[]
