import type { GemComponentDefinition } from './types'

// The names and broad identities come from the v0.4 canon. Numeric modifiers,
// compatibility and first-slice acquisition remain data-driven drafts.
export const gemComponentDefinitions = [
  {
    id: 'safira_mares',
    name: 'Safira das Marés',
    description: 'Canaliza água, cura e resistência ao calor.',
    rarity: 'rare',
    tier: 1,
    modifiers: [],
    activeEffectIds: [],
    skillTreeHooks: [],
    affinityTags: ['water', 'healing', 'heat-resistance'],
    compatibility: { anyEssenceTags: [], blockedEssenceTags: [] },
    visualTags: ['sapphire', 'tide-glow'],
    unique: false,
    iconAssetId: 'gem.sapphire-tides',
    status: 'CANON',
    mechanicsStatus: 'OWNER_DECISION',
  },
  {
    id: 'rubi_ira',
    name: 'Rubi da Ira',
    description: 'Canaliza força física, fogo e combustão.',
    rarity: 'rare',
    tier: 1,
    modifiers: [],
    activeEffectIds: [],
    skillTreeHooks: [],
    affinityTags: ['fire', 'physical', 'burning'],
    compatibility: { anyEssenceTags: [], blockedEssenceTags: [] },
    visualTags: ['ruby', 'ember-glow'],
    unique: false,
    iconAssetId: 'gem.ruby-wrath',
    status: 'CANON',
    mechanicsStatus: 'OWNER_DECISION',
  },
  {
    id: 'esmeralda_crescimento',
    name: 'Esmeralda do Crescimento',
    description: 'Estabiliza forças biológicas e suaviza toxinas por meio de crescimento arcano.',
    rarity: 'rare',
    tier: 1,
    modifiers: [
      { type: 'statModifier', stat: 'maxHp', operation: 'flat', value: 2 },
    ],
    activeEffectIds: [],
    skillTreeHooks: [
      'weapon_gem_focus_1',
      'weapon_gem_amplification_1',
      'weapon_synergy_mycelial_emerald_1',
    ],
    affinityTags: ['nature', 'growth', 'poison-resistance', 'biological'],
    compatibility: {
      anyEssenceTags: ['fungal', 'biological', 'nature', 'poison'],
      blockedEssenceTags: [],
    },
    visualTags: ['emerald', 'growth-veins'],
    unique: false,
    iconAssetId: 'gem.emerald-growth',
    status: 'CANON',
    mechanicsStatus: 'BALANCE_DRAFT',
  },
  {
    id: 'onix_sombra',
    name: 'Ônix da Sombra',
    description: 'Canaliza sombra, furtividade e ilusão.',
    rarity: 'epic',
    tier: 2,
    modifiers: [],
    activeEffectIds: [],
    skillTreeHooks: [],
    affinityTags: ['shadow', 'stealth', 'illusion'],
    compatibility: { anyEssenceTags: [], blockedEssenceTags: [] },
    visualTags: ['onyx', 'shadow-haze'],
    unique: false,
    iconAssetId: 'gem.onyx-shadow',
    status: 'CANON',
    mechanicsStatus: 'OWNER_DECISION',
  },
  {
    id: 'ametista_mente',
    name: 'Ametista da Mente',
    description: 'Canaliza proteção mental e forças psíquicas.',
    rarity: 'epic',
    tier: 2,
    modifiers: [],
    activeEffectIds: [],
    skillTreeHooks: [],
    affinityTags: ['mental', 'psychic', 'protection'],
    compatibility: { anyEssenceTags: [], blockedEssenceTags: [] },
    visualTags: ['amethyst', 'mind-aura'],
    unique: false,
    iconAssetId: 'gem.amethyst-mind',
    status: 'CANON',
    mechanicsStatus: 'OWNER_DECISION',
  },
  {
    id: 'topazio_relampago',
    name: 'Topázio do Relâmpago',
    description: 'Canaliza eletricidade, mana e eletrocussão.',
    rarity: 'epic',
    tier: 2,
    modifiers: [],
    activeEffectIds: [],
    skillTreeHooks: [],
    affinityTags: ['lightning', 'mana', 'shock'],
    compatibility: { anyEssenceTags: [], blockedEssenceTags: [] },
    visualTags: ['topaz', 'lightning-arc'],
    unique: false,
    iconAssetId: 'gem.topaz-lightning',
    status: 'CANON',
    mechanicsStatus: 'OWNER_DECISION',
  },
  {
    id: 'diamante_celestial',
    name: 'Diamante Celestial',
    description: 'Canaliza proteção extrema e vitalidade.',
    rarity: 'legendary',
    tier: 3,
    modifiers: [],
    activeEffectIds: [],
    skillTreeHooks: [],
    affinityTags: ['celestial', 'protection', 'vitality'],
    compatibility: { anyEssenceTags: [], blockedEssenceTags: [] },
    visualTags: ['diamond', 'celestial-radiance'],
    unique: false,
    iconAssetId: 'gem.diamond-celestial',
    status: 'CANON',
    mechanicsStatus: 'OWNER_DECISION',
  },
  {
    id: 'opala_caos',
    name: 'Opala do Caos',
    description: 'Canaliza teleporte, poder mágico e instabilidade.',
    rarity: 'legendary',
    tier: 3,
    modifiers: [],
    activeEffectIds: [],
    skillTreeHooks: [],
    affinityTags: ['chaos', 'teleport', 'arcane'],
    compatibility: { anyEssenceTags: [], blockedEssenceTags: [] },
    visualTags: ['opal', 'chaos-fracture'],
    unique: false,
    iconAssetId: 'gem.opal-chaos',
    status: 'CANON',
    mechanicsStatus: 'OWNER_DECISION',
  },
  {
    id: 'jade_eternidade',
    name: 'Jade da Eternidade',
    description: 'Canaliza longevidade e regeneração.',
    rarity: 'legendary',
    tier: 3,
    modifiers: [],
    activeEffectIds: [],
    skillTreeHooks: [],
    affinityTags: ['eternity', 'regeneration', 'vitality'],
    compatibility: { anyEssenceTags: [], blockedEssenceTags: [] },
    visualTags: ['jade', 'eternal-pulse'],
    unique: false,
    iconAssetId: 'gem.jade-eternity',
    status: 'CANON',
    mechanicsStatus: 'OWNER_DECISION',
  },
  {
    id: 'coracao_kethzar',
    name: "Coração de Keth'Zar",
    description: 'Canaliza força e resistência com um custo de vitalidade ainda não balanceado.',
    rarity: 'unique',
    tier: 4,
    modifiers: [],
    activeEffectIds: [],
    skillTreeHooks: [],
    affinityTags: ['strength', 'resistance', 'vitality-cost'],
    compatibility: { anyEssenceTags: [], blockedEssenceTags: [] },
    visualTags: ['kethzar-heart', 'blood-pulse'],
    unique: true,
    iconAssetId: 'gem.kethzar-heart',
    status: 'CANON',
    mechanicsStatus: 'OWNER_DECISION',
  },
] satisfies GemComponentDefinition[]
