import type { BoundItemBaseDefinition, ItemDefinition } from './types'

export const itemDefinitions = [
  {
    id: 'drop_fungal_nucleus',
    name: 'Núcleo Fúngico',
    description: 'Matéria orgânica impregnada pela energia de Astravél. Loot é potencial: converta ou venda.',
    category: 'drop',
    rarity: 'common',
    convertToEssence: true,
    essenceValue: 100,
    sellable: true,
    sellValue: 32,
    questLocked: false,
    canInfuseBoundItem: false,
    combatEffects: [],
    affinityTags: ['fungal', 'biological'],
    iconAssetId: 'item.fungal-nucleus',
    status: 'BALANCE_DRAFT',
  },
  {
    id: 'drop_spore_cluster',
    name: 'Aglomerado de Esporos',
    description: 'Resíduo instável da emboscada Fungorra. Pode virar Essência ou Ouro.',
    category: 'drop',
    rarity: 'uncommon',
    convertToEssence: true,
    essenceValue: 55,
    sellable: true,
    sellValue: 20,
    questLocked: false,
    canInfuseBoundItem: false,
    combatEffects: [],
    affinityTags: ['fungal', 'spore'],
    iconAssetId: 'item.spore-cluster',
    status: 'BALANCE_DRAFT',
  },
  {
    id: 'consumable_minor_tonic',
    name: 'Tônico de Campo',
    description: 'Preparado provisório encontrado no acampamento. Recupera Vida em combate.',
    category: 'consumable',
    rarity: 'common',
    convertToEssence: false,
    essenceValue: 0,
    sellable: false,
    sellValue: 0,
    questLocked: false,
    canInfuseBoundItem: false,
    combatEffects: [{ type: 'restoreHp', value: 8 }],
    affinityTags: ['healing', 'field-supply'],
    iconAssetId: 'item.minor-tonic',
    status: 'BALANCE_DRAFT',
  },
  {
    id: 'fragment_mycelial_essence',
    name: 'Fragmento de Essência Micelial',
    description: 'Fragmento de desenvolvimento ligado ao Colosso Micélio. É preservado para a Infusão do Grau II.',
    category: 'fragment',
    rarity: 'rare',
    convertToEssence: false,
    essenceValue: 0,
    sellable: false,
    sellValue: 0,
    questLocked: false,
    canInfuseBoundItem: true,
    infusionComponentId: 'essence_mycelial',
    combatEffects: [],
    affinityTags: ['fungal', 'biological', 'mycelial'],
    iconAssetId: 'item.mycelial-fragment',
    status: 'CONTENT_DRAFT',
  },
  {
    id: 'quest_astravel_record',
    name: 'Registro de Astravél',
    description: 'Anotação necessária para a investigação de Eldamar.',
    category: 'quest',
    rarity: 'unique',
    convertToEssence: false,
    essenceValue: 0,
    sellable: false,
    sellValue: 0,
    questLocked: true,
    canInfuseBoundItem: false,
    combatEffects: [],
    affinityTags: ['lore'],
    iconAssetId: 'item.quest-record',
    status: 'CONTENT_DRAFT',
  },
] satisfies ItemDefinition[]

export const boundItemBaseDefinitions: BoundItemBaseDefinition[] = [
  {
    id: 'bound_weapon_prologue_base',
    name: 'Arma Básica Vinculada',
    slot: 'weapon',
    archetype: 'blade',
    basePower: 3,
    treeId: 'tree_weapon_foundation',
    assetIdByGrade: {
      1: 'equipment.weapon.prologue.g1',
      2: 'equipment.weapon.prologue.g2',
    },
    status: 'CONTENT_DRAFT',
  },
]
