import type { SkillTreeNodeDefinition } from './types'

export const skillTreeNodeDefinitions = [
  {
    id: 'weapon_bond_core',
    treeId: 'tree_weapon_foundation',
    context: 'weapon',
    name: 'Núcleo do Vínculo',
    description: 'Estabiliza a primeira sintonia ofensiva entre o Terrírian e sua arma.',
    category: 'passive',
    costEssencePoints: 1,
    requires: [{ type: 'boundItemPresent', slot: 'weapon' }],
    hiddenUntil: [],
    effects: [{ type: 'statModifier', stat: 'attackPower', operation: 'flat', value: 1 }],
    position: { x: 50, y: 82 },
    iconAssetId: 'skill.weapon.bond-core',
    status: 'BALANCE_DRAFT',
  },
  {
    id: 'weapon_resonant_edge',
    treeId: 'tree_weapon_foundation',
    context: 'weapon',
    name: 'Corte Ressonante',
    description: 'A continuidade do vínculo melhora a pressão dos ataques básicos.',
    category: 'modifier',
    costEssencePoints: 1,
    requires: [
      { type: 'boundItemPresent', slot: 'weapon' },
      { type: 'previousNode', nodeId: 'weapon_bond_core' },
      { type: 'boundItemResonance', slot: 'weapon', value: 10 },
    ],
    hiddenUntil: [],
    effects: [{ type: 'statModifier', stat: 'attackPower', operation: 'flat', value: 1 }],
    position: { x: 34, y: 58 },
    iconAssetId: 'skill.weapon.resonant-edge',
    status: 'CONTENT_DRAFT',
  },
  {
    id: 'weapon_essence_channel',
    treeId: 'tree_weapon_foundation',
    context: 'weapon',
    name: 'Canal da Essência',
    description: 'Prepara o vínculo para interpretar seu primeiro Fragmento de Essência.',
    category: 'component',
    costEssencePoints: 1,
    requires: [
      { type: 'boundItemGrade', slot: 'weapon', value: 2 },
      { type: 'previousNode', nodeId: 'weapon_bond_core' },
    ],
    hiddenUntil: [],
    effects: [{ type: 'statModifier', stat: 'essenceGain', operation: 'multiply', value: 1.05 }],
    position: { x: 66, y: 58 },
    iconAssetId: 'skill.weapon.essence-channel',
    status: 'CONTENT_DRAFT',
  },
  {
    id: 'weapon_fungal_memory',
    treeId: 'tree_weapon_foundation',
    context: 'weapon',
    name: 'Memória Micelial',
    description: 'Um ramo revelado somente quando uma Essência de afinidade fúngica habita a arma.',
    category: 'memory',
    costEssencePoints: 2,
    requires: [
      { type: 'boundItemGrade', slot: 'weapon', value: 2 },
      { type: 'hasEssenceTag', slot: 'weapon', value: 'fungal' },
    ],
    hiddenUntil: [{ type: 'hasEssenceTag', slot: 'weapon', value: 'fungal' }],
    effects: [{ type: 'statModifier', stat: 'mitigation', operation: 'flat', value: 1 }],
    position: { x: 50, y: 32 },
    iconAssetId: 'skill.weapon.fungal-memory',
    status: 'CONTENT_DRAFT',
  },
  {
    id: 'shield_guard_foundation',
    treeId: 'tree_shield_foundation',
    context: 'shield',
    name: 'Postura Firme',
    description: 'A primeira disciplina de proteção do vínculo defensivo.',
    category: 'passive',
    costEssencePoints: 1,
    requires: [{ type: 'boundItemPresent', slot: 'shield' }],
    hiddenUntil: [],
    effects: [{ type: 'statModifier', stat: 'mitigation', operation: 'flat', value: 1 }],
    position: { x: 50, y: 72 },
    iconAssetId: 'skill.shield.guard-foundation',
    status: 'CONTENT_DRAFT',
  },
  {
    id: 'armor_survival_foundation',
    treeId: 'tree_armor_foundation',
    context: 'armor',
    name: 'Pele Vinculada',
    description: 'A fundação da resistência e adaptação da armadura.',
    category: 'passive',
    costEssencePoints: 1,
    requires: [{ type: 'boundItemPresent', slot: 'armor' }],
    hiddenUntil: [],
    effects: [{ type: 'statModifier', stat: 'maxHp', operation: 'flat', value: 2 }],
    position: { x: 50, y: 72 },
    iconAssetId: 'skill.armor.survival-foundation',
    status: 'CONTENT_DRAFT',
  },
  {
    id: 'necklace_flow_foundation',
    treeId: 'tree_necklace_foundation',
    context: 'necklace',
    name: 'Fluxo Interior',
    description: 'A fundação do modo como o poder circula dentro do Terrírian.',
    category: 'passive',
    costEssencePoints: 1,
    requires: [{ type: 'boundItemPresent', slot: 'necklace' }],
    hiddenUntil: [],
    effects: [{ type: 'statModifier', stat: 'essenceGain', operation: 'multiply', value: 1.03 }],
    position: { x: 50, y: 72 },
    iconAssetId: 'skill.necklace.flow-foundation',
    status: 'CONTENT_DRAFT',
  },
  {
    id: 'bracelet_execution_foundation',
    treeId: 'tree_bracelet_foundation',
    context: 'bracelet',
    name: 'Gesto Preciso',
    description: 'A fundação da execução, do movimento e da manipulação.',
    category: 'passive',
    costEssencePoints: 1,
    requires: [{ type: 'boundItemPresent', slot: 'bracelet' }],
    hiddenUntil: [],
    effects: [{ type: 'statModifier', stat: 'initiative', operation: 'flat', value: 1 }],
    position: { x: 50, y: 72 },
    iconAssetId: 'skill.bracelet.execution-foundation',
    status: 'CONTENT_DRAFT',
  },
] satisfies SkillTreeNodeDefinition[]
