import type { TerranLocationDefinition } from './types'

export const TERRAN_LOCATION_IDS = [
  'location_terran_eldamar_house',
  'location_terran_vorren_post',
  'location_terran_bond_workshop',
  'location_terran_zareth_barracks',
  'location_terran_clan_hall',
  'location_terran_daeryn_house',
  'location_terran_portal_plaza',
] as const

export type TerranLocationId = (typeof TERRAN_LOCATION_IDS)[number]

export const terranLocationDefinitions = [
  {
    id: 'location_terran_eldamar_house',
    settlementId: 'city_terran',
    name: 'Casa de Eldamar',
    shortName: 'Eldamar',
    verb: 'Compreender',
    role: 'Conhecimento, história e investigação',
    description: 'Registros, artefatos, documentos e pistas transformam acontecimentos em conhecimento útil para Terran.',
    category: 'institution',
    viewKind: 'eldamar',
    iconId: 'book',
    tone: 'knowledge',
    mapPosition: { x: 25, y: 20 },
    services: [
      { id: 'service_eldamar_lore', name: 'Lore e Codex', description: 'Consulta de registros e memórias descobertas.', state: 'available' },
      { id: 'service_eldamar_investigation', name: 'Investigação', description: 'Análise de pistas, documentos e artefatos.', state: 'available' },
      { id: 'service_eldamar_prologue', name: 'Prólogo', description: 'Introdução narrativa e primeiros rastros da campanha.', state: 'available' },
    ],
    npcPresences: [
      { id: 'presence_eldamar', label: 'Eldamar', npcId: 'npc_eldamar', presence: 'resident', roleLabel: 'Mestre dos Registros' },
      { id: 'presence_torvynn', label: 'Torvynn', presence: 'resident', roleLabel: 'Manuscritos e decifração' },
      { id: 'presence_gethin', label: 'Gethin', presence: 'resident', roleLabel: 'Histórias e memória oral' },
      { id: 'presence_elvira', label: 'Elvira', presence: 'conditional', roleLabel: 'Pergaminho oculto' },
    ],
    status: 'CANON',
  },
  {
    id: 'location_terran_vorren_post',
    settlementId: 'city_terran',
    name: 'Posto de Vorren',
    shortName: 'Vorren',
    verb: 'Descobrir',
    role: 'Caça, exploração e bestiário',
    description: 'Rastros, mapas, criaturas e materiais de campo são organizados antes e depois de cada expedição.',
    category: 'institution',
    viewKind: 'vorren',
    iconId: 'compass',
    tone: 'exploration',
    mapPosition: { x: 75, y: 20 },
    services: [
      { id: 'service_vorren_bestiary', name: 'Bestiário', description: 'Criaturas observadas, fraquezas e rastros.', state: 'available' },
      { id: 'service_vorren_hunting', name: 'Caça', description: 'Contratos e materiais ligados a criaturas.', state: 'progressive' },
      { id: 'service_vorren_mapping', name: 'Cartografia', description: 'Rotas, trilhas e descobertas de exploração.', state: 'available', route: '/world' },
    ],
    npcPresences: [
      { id: 'presence_vorren', label: 'Vorren', presence: 'resident', roleLabel: 'Caçador e rastreador' },
      { id: 'presence_elric', label: 'Elric', presence: 'resident', roleLabel: 'Caçador gentil' },
      { id: 'presence_draelis', label: 'Draelis', presence: 'resident', roleLabel: 'Rotas e acesso' },
      { id: 'presence_keldron', label: 'Keldron', presence: 'conditional', roleLabel: 'Caçador sombrio' },
      { id: 'presence_nerion', label: 'Nerion', presence: 'visitor', roleLabel: 'Cartógrafo celestial' },
    ],
    status: 'CANON',
  },
  {
    id: 'location_terran_bond_workshop',
    settlementId: 'city_terran',
    name: 'Oficina dos Vínculos',
    shortName: 'Oficina',
    verb: 'Evoluir',
    role: 'Itens vinculados e arquitetura da alma',
    description: 'Os cinco Vínculos são estudados e evoluídos com Ressonância, Essências, Joias, Runas, Memórias e Cicatrizes.',
    category: 'institution',
    viewKind: 'workshop',
    iconId: 'anvil',
    tone: 'bond',
    mapPosition: { x: 88, y: 52 },
    services: [
      { id: 'service_bond_items', name: 'Itens Vinculados', description: 'Inspeção dos cinco equipamentos permanentes.', state: 'available' },
      { id: 'service_bond_components', name: 'Essências, Joias e Runas', description: 'Componentes e compatibilidades por Grau.', state: 'available' },
      { id: 'service_bond_rites', name: 'Ritos de Evolução', description: 'Avanço de Grau mediante requisitos aprovados.', state: 'available' },
    ],
    npcPresences: [
      { id: 'presence_lithwynn', label: 'Lithwynn', presence: 'resident', roleLabel: 'Análise de corrupção' },
      { id: 'presence_valmira', label: 'Valmira', presence: 'resident', roleLabel: 'Artífice rúnica' },
      { id: 'presence_talia', label: 'Talia', presence: 'resident', roleLabel: 'Mestra do cristal' },
      { id: 'presence_edran', label: 'Edran', presence: 'resident', roleLabel: 'Gravador de símbolos' },
      { id: 'presence_feril', label: 'Feril', presence: 'resident', roleLabel: 'Guardião das pedras' },
      { id: 'presence_lorian', label: 'Lorian', presence: 'resident', roleLabel: 'Alquimia das inscrições' },
      { id: 'presence_durnan', label: 'Durnan', presence: 'conditional', roleLabel: 'Ferreiro errante' },
    ],
    status: 'CANON',
  },
  {
    id: 'location_terran_zareth_barracks',
    settlementId: 'city_terran',
    name: 'Quartel de Zareth',
    shortName: 'Zareth',
    verb: 'Proteger',
    role: 'Defesa, patrulhas e ameaças',
    description: 'A segurança de Terran é convertida em patrulhas, treinamento, contratos e resposta a ameaças conhecidas.',
    category: 'institution',
    viewKind: 'zareth',
    iconId: 'shield',
    tone: 'defense',
    mapPosition: { x: 73, y: 82 },
    services: [
      { id: 'service_zareth_bounties', name: 'Bounties', description: 'Inimigos procurados e contratos de ameaça.', state: 'progressive', route: '/quests' },
      { id: 'service_zareth_defense', name: 'Defesa de Terran', description: 'Alertas, patrulhas e ocorrências da cidade.', state: 'available' },
      { id: 'service_zareth_training', name: 'Treinamento', description: 'Preparação tática e provas de combate.', state: 'progressive' },
    ],
    npcPresences: [
      { id: 'presence_zareth', label: 'Capitão Zareth', presence: 'resident', roleLabel: 'Comando do Quartel' },
      { id: 'presence_kaedin', label: 'Kaedin', presence: 'resident', roleLabel: 'Vigia silencioso' },
      { id: 'presence_torvan', label: 'Torvan', presence: 'resident', roleLabel: 'Escudo de Terran' },
      { id: 'presence_dremor', label: 'Dremor', presence: 'resident', roleLabel: 'Último sentinela' },
      { id: 'presence_mireya', label: 'Mireya', presence: 'resident', roleLabel: 'Guardiã da Vigília' },
    ],
    status: 'CANON',
  },
  {
    id: 'location_terran_clan_hall',
    settlementId: 'city_terran',
    name: 'Salão dos Clãs',
    shortName: 'Clãs',
    verb: 'Tornar-se',
    role: 'Clã, Classe e Main Lore',
    description: 'Representantes, mestres, provas e ritos transformam relações conquistadas em pertencimento, Classe e participação na história central.',
    category: 'institution',
    viewKind: 'clanHall',
    iconId: 'clan',
    tone: 'clan',
    mapPosition: { x: 27, y: 82 },
    services: [
      { id: 'service_clan_affiliation', name: 'Filiação de Clã', description: 'Reputação, provas e rito de ingresso.', state: 'progressive' },
      { id: 'service_class_paths', name: 'Caminhos de Classe', description: 'Disciplinas desenvolvidas dentro do Clã.', state: 'progressive' },
      { id: 'service_main_lore', name: 'Main Lore', description: 'Conselho e campanha central após progressão social.', state: 'progressive', route: '/quests' },
    ],
    npcPresences: [
      { id: 'presence_dunavar_rep', label: 'Mireya Dûn’Avar', npcId: 'npc_mireya_dunavar', presence: 'institution', roleLabel: 'Recrutamento Dûn’Avar' },
      { id: 'presence_rustal_rep', label: 'Mestre Rustal', npcId: 'npc_master_rustal', presence: 'institution', roleLabel: 'Recrutamento Rustal' },
      { id: 'presence_cebios_rep', label: 'Observador Cebios', npcId: 'npc_observador_cebios', presence: 'institution', roleLabel: 'Recrutamento Cebios Esti' },
      { id: 'presence_estres_rep', label: 'Guardador do Ét', npcId: 'npc_guardador_estres', presence: 'institution', roleLabel: 'Recrutamento Estres do Ét' },
      { id: 'presence_class_masters', label: 'Mestres de Classe', presence: 'progressive', roleLabel: 'Treino após filiação' },
      { id: 'presence_main_lore_council', label: 'Curador do Nexo', npcId: 'npc_curador_nexo', presence: 'progressive', roleLabel: 'Main Lore após Classe' },
    ],
    status: 'CANON',
  },
  {
    id: 'location_terran_daeryn_house',
    settlementId: 'city_terran',
    name: 'Casa de Daeryn',
    shortName: 'Daeryn',
    verb: 'Preparar-se',
    role: 'Cura, alquimia e preparação',
    description: 'Tratamentos, poções, antídotos, herbalismo e resistências temporárias preparam o jogador para ameaças específicas.',
    category: 'institution',
    viewKind: 'daeryn',
    iconId: 'flask',
    tone: 'healing',
    mapPosition: { x: 12, y: 52 },
    services: [
      { id: 'service_daeryn_healing', name: 'Cura', description: 'Recuperação e tratamento de condições.', state: 'available' },
      { id: 'service_daeryn_alchemy', name: 'Alquimia', description: 'Poções, antídotos e materiais herbais.', state: 'progressive' },
      { id: 'service_daeryn_preparation', name: 'Preparação', description: 'Resistências temporárias para uma expedição.', state: 'progressive' },
    ],
    npcPresences: [
      { id: 'presence_daeryn', label: 'Daeryn', presence: 'resident', roleLabel: 'Curandeira' },
      { id: 'presence_sylwen', label: 'Sylwen', presence: 'resident', roleLabel: 'Criadora de poções' },
      { id: 'presence_briana', label: 'Briana', presence: 'resident', roleLabel: 'Herbalista' },
      { id: 'presence_orlan', label: 'Orlan', presence: 'conditional', roleLabel: 'Herbalista solitário' },
    ],
    status: 'CANON',
  },
  {
    id: 'location_terran_portal_plaza',
    settlementId: 'city_terran',
    name: 'Praça do Portal',
    shortName: 'Portal',
    verb: 'Partir',
    role: 'Acesso autorizado às instâncias',
    description: 'O centro de Terran registra partidas e retornos. O Portal executa expedições autorizadas; não cria nem substitui as missões da cidade.',
    category: 'portal',
    viewKind: 'portal',
    iconId: 'portal',
    tone: 'portal',
    mapPosition: { x: 50, y: 50 },
    services: [
      { id: 'service_portal_validation', name: 'Validar missão', description: 'Confere missão ativa, autorização e pré-requisitos.', state: 'available' },
      { id: 'service_portal_dispatch', name: 'Acessar instância', description: 'Apresenta objetivo, perigo e recompensas conhecidas.', state: 'available' },
      { id: 'service_portal_registry', name: 'Registro de expedição', description: 'Registra partida e retorno a Terran.', state: 'available' },
    ],
    npcPresences: [
      { id: 'presence_portal_guardian', label: 'Guardião do Portal', presence: 'resident', roleLabel: 'Validação e registro de expedições' },
    ],
    status: 'CANON',
  },
] satisfies TerranLocationDefinition[]
